# -*- coding: utf-8 -*-
"""Info Retrieval to JSON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNwg2Hz2LXKZS6o7gWLchkSBMdBhooBH

# Web Information Retrieval Workshop for Space News, Policy, and Doctrine

This workshop collects and triages reputable space-related information from the web. It focuses on:

- Curated, reputable sources (news outlets, policy think tanks, official agencies)
- RSS-based harvesting (fast, low-friction)
- Optional article fetching and summarization
- Interactive filtering and export

Must be connected to the Internet.

## 0) Install Dependencies (one time)

Run the cell below once. If you restart the kernel, you may need to re-run it.

Packages used:
- `feedparser` — parse RSS/Atom feeds
- `trafilatura` — robust article/download text extraction (fallbacks to readability)
- `newspaper3k` — optional article parsing (some sites block; trafilatura often works better)
- `beautifulsoup4` — HTML parsing in a pinch
- `pandas` — data wrangling
- `scikit-learn` — simple deduplication via TF–IDF cosine similarity
- `ipywidgets` — interactive UI
"""

import sys, subprocess
def pip_install(pkg):
    print('Installing', pkg)
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg])

for p in [
    'feedparser', 'trafilatura', 'newspaper3k', 'beautifulsoup4',
    'pandas', 'scikit-learn', 'ipywidgets'
]:
    try:
        __import__(p.split('==')[0].split('[')[0])
    except Exception:
        pip_install(p)

import pandas as pd
import feedparser
import re
from datetime import datetime, timedelta
from urllib.parse import urlparse
from IPython.display import display, HTML

try:
    import trafilatura
except Exception as e:
    trafilatura = None
try:
    from newspaper import Article
except Exception:
    Article = None

try:
    import ipywidgets as widgets
    from ipywidgets import interact, interactive_output
    HAVE_WIDGETS = True
except Exception:
    HAVE_WIDGETS = False
    print('ipywidgets not available; falling back to non-interactive usage.')

"""## 1) Trusted Source Registry

Below is a curated list of broadly reputable sources. You can add/remove rows as needed to `sources_df` with additional RSS feeds or specific topical blogs.

```
new = {"name": "Your Source", "domain": "example.org", "category": "Policy/News", "rss": "https://example.org/feed"}
sources_df = pd.concat([sources_df, pd.DataFrame([new])], ignore_index=True)
```

Feeds are RSS/Atom where possible (these are more stable, but do not provide full details).
"""

SOURCES = [
    # --- Space Agencies / Official News ---
    {"name": "NASA Breaking News", "domain": "nasa.gov", "category": "News", "rss": "https://www.nasa.gov/rss/dyn/breaking_news.rss"},
    {"name": "ESA Newsroom", "domain": "esa.int", "category": "News", "rss": "https://www.esa.int/rssfeed/Our_Activities"},
    {"name": "ESA Space Safety (Blog)", "domain": "esa.int", "category": "Policy/SSA", "rss": "https://www.esa.int/feeds/ESA_Space_Safety_Blog"},
    {"name": "JAXA Global Press", "domain": "jaxa.jp", "category": "News", "rss": "https://global.jaxa.jp/rss/rss.xml"},
    {"name": "UK Space Agency", "domain": "gov.uk", "category": "Policy/News", "rss": "https://www.gov.uk/government/organisations/uk-space-agency.atom"},
    {"name": "CNES News", "domain": "cnes.fr", "category": "News", "rss": "https://cnes.fr/en/rss.xml"},
    {"name": "DLR News", "domain": "dlr.de", "category": "News", "rss": "https://www.dlr.de/SiteTools/Functions/RSSFeeds/EN/RSSNewsFeed.xml"},
    {"name": "ASI News", "domain": "asi.it", "category": "News", "rss": "https://www.asi.it/en/feed/"},

    # --- Region-specific (CNSA/ISRO/Roscosmos/UNOOSA, commercial China) --
    {"name": "CNSA (mirror/English)", "domain": "cnsa.gov.cn", "category": "News", "rss": "https://www.cnsa.gov.cn/english/rss.xml"},
    {"name": "ISRO Updates", "domain": "isro.gov.in", "category": "News", "rss": "https://www.isro.gov.in/rss.xml"},
    {"name": "Roscosmos News", "domain": "roscosmos.ru", "category": "News", "rss": "https://www.roscosmos.ru/rss/en/"},
    {"name": "UNOOSA News", "domain": "unoosa.org", "category": "Policy/UN", "rss": "https://www.unoosa.org/oosa/rss.xml"},
    {"name": "CASC Press Releases", "domain": "spacechina.com", "category": "Industry", "rss": "https://www.spacechina.com/n25/n144/n2066/index.html"},
    {"name": "CASIC News", "domain": "casic.com.cn", "category": "Industry", "rss": "https://www.casic.com.cn/rss.xml"},

    # # --- Regulation / Spectrum / STM ---
    {"name": "FCC News Releases", "domain": "fcc.gov", "category": "Regulation", "rss": "https://www.fcc.gov/news-events/rss/releases.xml"},
    {"name": "FAA Newsroom (AST)", "domain": "faa.gov", "category": "Regulation", "rss": "https://www.faa.gov/newsroom/rss.xml"},
    {"name": "ITU News", "domain": "itu.int", "category": "Spectrum/Policy", "rss": "https://news.itu.int/feed/"},
    {"name": "NTIA News", "domain": "ntia.doc.gov", "category": "Spectrum/Policy", "rss": "https://www.ntia.gov/rss"},
    {"name": "Ofcom Features & News", "domain": "ofcom.org.uk", "category": "Spectrum/Policy", "rss": "https://www.ofcom.org.uk/about-ofcom/latest/features-and-news/rss"},

    # # --- Defense / Military Official ---
    {"name": "US Space Force News", "domain": "spaceforce.mil", "category": "Defense", "rss": "https://www.spaceforce.mil/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=106&max=50"},
    {"name": "US Space Command News", "domain": "spacecom.mil", "category": "Defense", "rss": "https://www.spacecom.mil/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=323&max=50"},

    # # --- Think Tanks / NGOs / Research ---
    {"name": "Secure World Foundation", "domain": "swfound.org", "category": "Policy/NGO", "rss": "https://swfound.org/news/rss/"},
    {"name": "CSIS Aerospace Security", "domain": "csis.org", "category": "Policy/Research", "rss": "https://www.csis.org/rss.xml"},
    {"name": "Aerospace Corporation", "domain": "aerospace.org", "category": "Policy/Research", "rss": "https://aerospace.org/rss.xml"},
    {"name": "European Space Policy Institute (ESPI)", "domain": "espi.or.at", "category": "Policy/Research", "rss": "https://www.espi.or.at/feed/"},

    # --- Independent/Trade News & Analysis ---
    {"name": "SpaceNews", "domain": "spacenews.com", "category": "News", "rss": "https://spacenews.com/feed/"},
    {"name": "SpacePolicyOnline", "domain": "spacepolicyonline.com", "category": "Policy/News", "rss": "https://spacepolicyonline.com/feed/"},
    {"name": "SpaceWatch.Global", "domain": "spacewatch.global", "category": "News", "rss": "https://spacewatch.global/feed/"},
    {"name": "The Space Review", "domain": "thespacereview.com", "category": "Analysis/Opinion", "rss": "http://www.thespacereview.com/rss.xml"},

    # --- Commercial SDA / STM (blogs) ---
    {"name": "LeoLabs Blog", "domain": "leolabs.space", "category": "SSA/STM", "rss": "https://blog.leolabs.space/rss/"},
]

sources_df = pd.DataFrame(SOURCES)
display(sources_df)

"""## 1.a) Preset Keyword Watchlists
Tailored for debris, spectrum policy, RPO, and SSA/STM. You can modify these profiles and pass them into the UI query box or script calls.
"""

WATCHLISTS = {
    'debris': [
        'debris', 'ASAT', 'anti-satellite', 'conjunction', 'fragmentation', 'ODQN', 'IADC', 'mitigation', 'reentry', 'post-mission disposal'
    ],
    'spectrum_policy': [
        'spectrum', 'licensing', 'ITU', 'WRC', 'Article 22', 'NTIA', 'ITU-R', 'Ka-band', 'Ku-band', 'LEO interference', 'coordination'
    ],
    'rpo': [
        'RPO', 'proximity operations', 'docking', 'grapple', 'inspection', 'rendezvous', 'on-orbit servicing', 'non-cooperative'
    ],
    'ssa_stm': [
        'SSA', 'STM', 'tracking', 'catalog', 'space traffic', 'conjunction assessment', 'COLA', 'space situational awareness'
    ],
}

def join_watchlist(name):
    terms = WATCHLISTS.get(name, [])
    return ' OR '.join(sorted(set(terms)))

print('Example watchlist query (RPO):')
print(join_watchlist('rpo'))

"""## 2) Helpers: Fetch Feeds, Normalize, Optional Summaries

These functions help with the IR task.

- `fetch_feed` — downloads RSS entries
- `clean_text` — small sanitizer
- `fetch_article_text` — attempts to extract full text using `trafilatura` first, then `newspaper3k`
- `summarize_text` — naive summary via sentence scoring (length + keyword hits)
"""

import math, time, html

def clean_text(t: str) -> str:
    if not t:
        return ''
    t = html.unescape(t)
    t = re.sub(r'<[^>]+>', ' ', t)
    t = re.sub(r'\s+', ' ', t).strip()
    return t

def fetch_feed(feed_url: str, limit: int = 50):
    try:
        fp = feedparser.parse(feed_url)
        entries = []
        for e in fp.entries[:limit]:
            title = clean_text(getattr(e, 'title', ''))
            link = getattr(e, 'link', '')
            summary = clean_text(getattr(e, 'summary', ''))
            published = None
            if getattr(e, 'published_parsed', None):
                published = datetime(*e.published_parsed[:6])
            elif getattr(e, 'updated_parsed', None):
                published = datetime(*e.updated_parsed[:6])
            entries.append({
                'title': title,
                'link': link,
                'summary': summary,
                'published': published,
                'source': urlparse(feed_url).netloc,
                'feed': feed_url,
            })
        return entries
    except Exception as ex:
        print('Feed error:', feed_url, ex)
        return []

def fetch_article_text(url: str, timeout: int = 15):
    text = ''
    # Try trafilatura first
    if trafilatura is not None:
        try:
            downloaded = trafilatura.fetch_url(url, timeout=timeout)
            if downloaded:
                text = trafilatura.extract(downloaded) or ''
        except Exception:
            pass
    # Fallback to newspaper3k
    if not text and Article is not None:
        try:
            art = Article(url)
            art.download()
            art.parse()
            text = art.text or ''
        except Exception:
            pass
    return clean_text(text)

def summarize_text(text: str, query_terms=None, max_sentences=4):
    if not text:
        return ''
    sents = re.split(r'(?<=[.!?])\s+', text)
    if not sents:
        return text[:400] + '...'
    query_terms = [t.lower() for t in (query_terms or []) if t.strip()]
    scores = []
    for i, s in enumerate(sents):
        length_score = min(len(s) / 200, 1.0)
        term_score = sum(s.lower().count(q) for q in query_terms)
        scores.append((length_score + term_score, i, s))
    scores.sort(reverse=True)
    chosen = [s for _, _, s in scores[:max_sentences]]
    chosen.sort(key=lambda x: sents.index(x))
    return ' '.join(chosen)

"""## 3) Harvest Feeds → DataFrame
Choose which sources to harvest, how many items per feed, and an optional time window.
"""

import nltk
nltk.download('punkt')

"""# 3a) Run This Block to Delete Previous Versions of harvested_articles.json to Start From Scratch"""

import os

output_file = "harvested_articles.json"

if os.path.exists(output_file):
    os.remove(output_file)
    print(f"🗑️ Deleted old file: {output_file}")
else:
    print("No existing harvested_articles.json found — starting fresh.")

import json
import os
from newspaper import Article
from datetime import datetime

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

def extract_article_data(url):
    """Extract main text and publish date from an article using newspaper3k."""
    try:
        article = Article(url)
        article.download()
        article.parse()
        text = article.text.strip()
        published_date = article.publish_date
        return text, published_date
    except Exception as e:
        print(f"Error parsing {url}: {e}")
        return "", None

def export_articles_to_json(df, output_file="harvested_articles.json"):
    """
    Extract article text + date and append to JSON file.
    Includes title, source_name, category, summary, published, text, and link.
    """

    # Load existing JSON data if file exists
    if os.path.exists(output_file):
        with open(output_file, "r", encoding="utf-8") as f:
            try:
                existing_articles = json.load(f)
            except json.JSONDecodeError:
                existing_articles = []
    else:
        existing_articles = []

    # Build set of (title, source_name) to detect duplicates
    existing_ids = set(
        (art.get("title", "").strip(), art.get("source_name", "").strip())
        for art in existing_articles
    )

    new_articles = []
    for _, row in df.iterrows():
        key = (row.get("title", "").strip(), row.get("source_name", "").strip())
        if key in existing_ids:
            continue  # Skip duplicate

        text, article_date = extract_article_data(row.get("link", ""))

        # Use feed date if available; otherwise use newspaper3k's date
        published = (
            row.get("published")
            if pd.notnull(row.get("published"))
            else article_date
        )

        # Normalize to ISO string
        if isinstance(published, datetime):
            published_str = published.isoformat()
        elif published:
            published_str = str(published)
        else:
            published_str = ""

        article_entry = {
            "title": row.get("title", ""),
            "source_name": row.get("source_name", ""),
            "category": row.get("category", ""),
            "summary": row.get("summary", ""),
            "published": published_str,
            "text": text,
            "link": row.get("link", "")
        }

        new_articles.append(article_entry)
        existing_ids.add(key)

    if not new_articles:
        print("⚠️ No new articles to add (all duplicates).")
        return

    # Append and write back to file
    all_articles = existing_articles + new_articles
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(all_articles, f, ensure_ascii=False, indent=2)

    print(f"✅ Added {len(new_articles)} new articles. Total: {len(all_articles)} in {output_file}")

DEFAULT_LIMIT = 30
def harvest(sources_table, include_categories=None, limit=DEFAULT_LIMIT, days_back=30):
    include_categories = set(include_categories or [])
    rows = []
    cutoff = datetime.now() - timedelta(days=days_back)
    for _, row in sources_table.iterrows():
        if include_categories and row['category'] not in include_categories:
            continue
        entries = fetch_feed(row['rss'], limit=limit)
        for e in entries:
            if e['published'] and e['published'] < cutoff:
                continue
            e['source_name'] = row['name']
            e['category'] = row['category']
            rows.append(e)
    if not rows:
        return pd.DataFrame(columns=['published','title','source_name','category','summary','link','feed'])
    df = pd.DataFrame(rows)
    df = df.sort_values(by=['published'], ascending=False, na_position='last').reset_index(drop=True)
    return df

df = harvest(
    sources_df,
    include_categories={'News', 'Policy/SSA', 'Policy/News', 'Policy/UN', 'Industry', 'Regulation', 'Spectrum/Policy', 'Defense', 'Policy/NGO', 'Policy/Research', 'Analysis/Opinion', 'SSA/STM'}
)

export_articles_to_json(df)  # or df for all

# """## 4) Query + Filter + (Optional) Summarize
# Here is a function that allows you to use keywords and filters to triage the harvested items. You can optionally fetch the full article text and produce a quick extractive summary.
# """

# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import cosine_similarity

# def filter_and_enrich(df, query:str='', sources=None, categories=None, fetch_full=False, summarize=False, top_k=50):
#     if df is None or df.empty:
#         return df
#     filt = df.copy()
#     if sources:
#         filt = filt[filt['source_name'].isin(sources)]
#     if categories:
#         filt = filt[filt['category'].isin(categories)]
#     if query:
#         q = query.lower()
#         mask = (
#             filt['title'].str.lower().str.contains(q, na=False) |
#             filt['summary'].str.lower().str.contains(q, na=False)
#         )
#         filt = filt[mask]
#     filt = filt.copy().reset_index(drop=True)

#     # Lightweight dedup by title similarity
#     if len(filt) > 1:
#         vec = TfidfVectorizer(stop_words='english').fit_transform(filt['title'].fillna(''))
#         sim = cosine_similarity(vec)
#         to_drop = set()
#         for i in range(len(filt)):
#             if i in to_drop: continue
#             for j in range(i+1, len(filt)):
#                 if sim[i,j] >= 0.85:
#                     to_drop.add(j)
#         if to_drop:
#             filt = filt.drop(index=list(to_drop)).reset_index(drop=True)

#     if fetch_full or summarize:
#         texts = []
#         for i, row in filt.iterrows():
#             if fetch_full:
#                 txt = fetch_article_text(row['link'])
#             else:
#                 txt = ''
#             if summarize and txt:
#                 summ = summarize_text(txt, query_terms=query.split())
#             else:
#                 summ = row.get('summary','')
#             texts.append((txt, summ))
#         if texts:
#             filt['full_text'] = [t[0] for t in texts]
#             filt['summary'] = [t[1] for t in texts]

#     return filt.head(top_k)

# """## 5) Interactive UI
# If `ipywidgets` is available, use the controls to harvest, filter, summarize, and export.
# """

# if HAVE_WIDGETS:
#     cat_opts = sorted(sources_df['category'].unique())
#     src_opts = sorted(sources_df['name'].unique())

#     w_categories = widgets.SelectMultiple(options=cat_opts, value=tuple(cat_opts), description='Categories', layout=widgets.Layout(width='300px', height='150px'))
#     w_sources = widgets.SelectMultiple(options=src_opts, value=(), description='Sources', layout=widgets.Layout(width='300px', height='200px'))
#     w_limit = widgets.IntSlider(value=30, min=5, max=100, step=5, description='Items/feed')
#     w_days = widgets.IntSlider(value=30, min=1, max=180, step=1, description='Days back')
#     w_query = widgets.Text(value='', description='Keywords', placeholder='e.g., spectrum, debris, ITU, RPO, policy')
#     w_fetch = widgets.Checkbox(value=False, description='Fetch full text')
#     w_summarize = widgets.Checkbox(value=False, description='Auto-summarize')
#     w_topk = widgets.IntSlider(value=50, min=5, max=200, step=5, description='Top K')
#     w_button = widgets.Button(description='Run Harvest ▶', button_style='success')
#     w_export = widgets.Button(description='Export CSV 💾', button_style='')
#     w_out = widgets.Output()

#     state = {'df': None, 'filt': None}

#     def on_run_clicked(b):
#         with w_out:
#             w_out.clear_output()
#             print('Harvesting...')
#             cats = set(w_categories.value)
#             df = harvest(sources_df, include_categories=cats, limit=w_limit.value, days_back=w_days.value)
#             state['df'] = df
#             print(f'Harvested {len(df)} items.')
#             print('Filtering...')
#             filt = filter_and_enrich(
#                 df, query=w_query.value,
#                 sources=list(w_sources.value) if w_sources.value else None,
#                 categories=list(cats),
#                 fetch_full=w_fetch.value,
#                 summarize=w_summarize.value,
#                 top_k=w_topk.value
#             )
#             state['filt'] = filt
#             if filt is None or filt.empty:
#                 print('No results.')
#             else:
#                 display(filt[['published','source_name','category','title','summary','link']])

#     def on_export_clicked(b):
#         with w_out:
#             if state.get('filt') is None or state['filt'].empty:
#                 print('Nothing to export. Run a harvest first.')
#                 return
#             ts = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
#             path = f'space_info_retrieval_{ts}.csv'
#             state['filt'].to_csv(path, index=False)
#             print(f'Exported to {path}')

#     w_button.on_click(on_run_clicked)
#     w_export.on_click(on_export_clicked)

#     ui = widgets.HBox([
#         widgets.VBox([w_categories, w_sources]),
#         widgets.VBox([w_query, w_limit, w_days, w_topk, w_fetch, w_summarize, widgets.HBox([w_button, w_export])])
#     ])
#     display(ui, w_out)
# else:
#     print('Widgets not available. Use the functions below directly. For example:')
#     print("df = harvest(sources_df, include_categories={'News','Policy/News'}, limit=25, days_back=30)")
#     print("res = filter_and_enrich(df, query='debris', fetch_full=False, summarize=False, top_k=50)")
#     print('display(res.head(10))')

# """## 6) Non-interactive Example (Script-style)
# If you're running headless or without `ipywidgets`, use the snippet below.
# """

# # Example script usage:
# example_df = harvest(sources_df, include_categories={'News','Policy/News','Regulation'}, limit=20, days_back=14)
# example_res = filter_and_enrich(example_df, query='debris OR spectrum OR RPO', fetch_full=False, summarize=False, top_k=30)
# display(example_res[['published','source_name','title','link']].head(10))

# """## 7) Tips: Vetting Source Credibility

# - Prefer official domains for regulations (e.g., `.gov`, space agency sites)
# - Use think tanks with transparent methods and citations (e.g., SWF, CSIS, Aerospace Corp.)
# - Beware of scraped aggregators without original reporting
# - Cross-check across at least **two** independent sources for consequential claims
# - Archive URLs (e.g., via *Perma.cc* or *Internet Archive*) for long-term reference

# ## 9) Limitations & Alternatives

# **Technical limitations**
# - Sequential RSS fetch by default (~1–3 feeds/sec typical). Consider polite concurrency per-domain if you add `asyncio`.
# - No CAPTCHA/anti-bot evasion; JavaScript-heavy sites and Cloudflare-protected pages may fail.
# - Ads/paywalls: RSS often provides snippets only; full-text extraction may return partial or noisy text.
# - Basic keyword filtering and TF–IDF dedup — not a semantic search engine.
# - Limited historical depth; RSS feeds usually expose only the latest 20–50 items.

# **Ethical & legal**
# - Always honor Terms of Service and robots.txt; do not attempt to bypass access controls.
# - Prefer official feeds/APIs; archive links responsibly for research reproducibility.

# **When to use paid APIs (Brave Search, Serper, Bing, etc.)**
# - Need large-scale discovery across many domains with relevance ranking.
# - Require higher throughput (tens–hundreds of QPS) with SLAs and uptime.
# - Want structured metadata (author/site rank/date) and stable, legal access without scraping fragility.

# **Hybrid workflow suggestion**
# - Use this notebook for continuous monitoring of trusted sources (NASA/ESA/USSF/etc.).
# - Use a paid search API for broad discovery (e.g., historic mentions of RPO or spectrum filings).
# - Store results in a local database (CSV/SQLite) on a schedule for longitudinal analysis.

# ## 10) APIs

# **Brave Search API**
# - https://brave.com/search/api/
# - https://github.com/kayvane1/brave-api

# **Serper API**
# - https://serper.dev/
# - https://python.langchain.com/docs/integrations/providers/google_serper/

# **SerpAPI**
# - https://serpapi.com/
# """